[build]
  publish = "dist/"
  command = "grunt build --target=build"

[context.branch-deploy]
  environment = { OPENSENSEMAP_STYLE_URL = "", OPENSENSEMAP_ACCESS_TOKEN = "", OPENSENSEMAP_API_URL = "https://api.testing.opensensemap.org" }

[[headers]]
  for = "/*"

  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Cache-Control = "public, max-age: 300"

[[headers]]
  for = "/scripts"

  [headers.values]
    Expires = "Thu, 31 Dec 2037 23:55:55 GMT"
    Cache-Control = "public"

[[headers]]
  for = "/styles"

  [headers.values]
    Expires = "Thu, 31 Dec 2037 23:55:55 GMT"
    Cache-Control = "public"

[[headers]]
  for = "/fonts"

  [headers.values]
    Expires = "Thu, 31 Dec 2037 23:55:55 GMT"
    Cache-Control = "public"

[[redirects]]
  from="/explore/*"
  to="/"
  status=200

[[redirects]]
  from="/account"
  to="/"
  status=200

[[redirects]]
  from="/interpolation"
  to="/"
  status=200

[[redirects]]
  from="/filter"
  to="/"
  status=200

[[redirects]]
  from="/download"
  to="/"
  status=200

[[redirects]]
  from="/register"
  to="/"
  status=200

[[redirects]]
  from="/about"
  to="/"
  status=200

[[redirects]]
  from="/imprint"
  to="/"
  status=200

[[redirects]]
  from="/privacy"
  to="/"
  status=200

[template.environment]
  OPENSENSEMAP_MAPTILES_URL = "Maptiles url"
  OPENSENSEMAP_API_URL = "API endpoint"